version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - .:/home/dev/FastApi/

  redis:
    image: redis:latest
    networks:
      - mynetwork

networks:
  mynetwork:
